German Tech Podcasts: Basic filter
EngineeringKiosk/webpage pull request #224
Opened 2022-10-18 17:32 UTC by andygrunwald

This pull request adds a basic filter for the german tech podcast listing.

2022-10-21 10:47 UTC, woolfg requested changes
- filter works very well :+1: 
- why having two filter options that do the same? de traffic light is difficult to understand and the other filter is straight forward as it explains what it does. I would remove the first filter option.
- It would be cool to show the number of results, otherwise as a user you don't see a change in the list if the first podcast stays the same. a number would always change when changing the filters.
- for mobile the filters are out of the view 
![image](https://user-images.githubusercontent.com/1328269/197178158-b5ddb73c-220e-4dcb-ab3e-bcdbe3be6ecc.png)
- filter reseetten -> Filter zurücksetzen
- if there is just one filter option I think the button "reset" is no longer needed as it can simply be changed back to "all"

2022-10-22 10:00 UTC, andygrunwald commented
@woolfg Please review again. I changed:

* Removed the "Podcast Status Traffic Light filter"
* Added a Filter count

2022-10-22 11:11 UTC, woolfg commented
fixed some smaller mobile issues.

2022-10-22 11:12 UTC, woolfg approved these changes

2022-10-22 11:12 UTC, merged