:art: consider upcoming and passed meetings (remove necessity for mdx)
EngineeringKiosk/webpage pull request #603
Opened 2023-10-29 12:45 UTC by romedius

ok - got rid of the mdx files.

split up the allMetups into a filtered newMeetups array and used passedMeetups for the archive

2023-10-29 17:06 UTC, timhannemann requested changes
perfect, but I think it is important that we show the meetup longer that till the startdate! See my suggestion!

2023-10-29 17:06 UTC, timhannemann commented on src/pages/meetup/alps/promote.astro
> +let upcomingMeetups = allMeetups.filter((meetup) => new Date(meetup.frontmatter.date) > new Date());
same as above

2023-10-30 11:30 UTC, woolfg commented on src/components/MeetupListing.astro
> +let upcomingMeetups = allMeetups.filter((meetup) => new Date(meetup.frontmatter.date) > new Date());
or maybe even +48 hours?

2023-10-30 11:33 UTC, woolfg commented on src/components/MeetupListing.astro
> +let upcomingMeetups = allMeetups.filter((meetup) => new Date(meetup.frontmatter.date) > new Date());
I would suggest to move the whole logic of fetching meetups to a separate file providing a fetch function that takes an argument to specify what meetups are needed.

2023-10-30 11:36 UTC, woolfg commented on src/pages/meetup/alps/index.astro
in this file we fetch all information to use on the index page and then use <MeetupListing> which fetches all information again. maybe we can just use an argument on MeetupListing which takes the meetups? the outer scope is then responsible to the fetch the needed meetups.

2023-10-30 22:18 UTC, timhannemann commented on src/components/MeetupListing.astro
> +let upcomingMeetups = allMeetups.filter((meetup) => new Date(meetup.frontmatter.date) > new Date());
why 48h?
central fetching and params would be good, yes!

2023-10-30 23:15 UTC, woolfg commented on src/components/MeetupListing.astro
> +let upcomingMeetups = allMeetups.filter((meetup) => new Date(meetup.frontmatter.date) > new Date());
- if people want to lookup something on the next day, it is still there and not in the archive yet.
- in general it is not exact, as it is just updated when an commit triggers the build of the website, although that happens quite often as we have a lot of triggers and auto-updates.

2023-11-01 16:44 UTC, timhannemann commented on src/components/MeetupListing.astro
> +let upcomingMeetups = allMeetups.filter((meetup) => new Date(meetup.frontmatter.date) > new Date());
isn't there some nightly workflow running anyway? but yes, some time-delay would be nice, 24 or 48 hours - I don't care...

2023-11-01 21:24 UTC, woolfg commented on src/components/MeetupListing.astro
> +let upcomingMeetups = allMeetups.filter((meetup) => new Date(meetup.frontmatter.date) > new Date());
there is just a weekly on tuesday, but hopefully we always add the slides on the next day anyways ;)

2023-11-02 16:51 UTC, romedius commented
hi!

@woolfg , sag ma einfach auf was ich das einstellen soll - ich modularisiers mal raus und machs irgendwie konfigurierbar.

IMHO: Wenns ne gute Verbesserung ist, im Zweifel mal mergen und dann darauf aufbauen - sowohl modularisierung als auch die Zeitverschiebung :)

2023-11-16 14:38 UTC, merged